// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptTracker.Infrastructure.Data;

#nullable disable

namespace ReceiptTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328170637_ExpandReceiptDataFixed")]
    partial class ExpandReceiptDataFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReceiptTracker.Core.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CountryRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("CountryRegionConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double?>("MerchantNameConfidence")
                        .HasColumnType("float");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ReceiptTypeConfidence")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("TotalAmountConfidence")
                        .HasColumnType("float");

                    b.Property<decimal?>("TotalTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("TotalTaxConfidence")
                        .HasColumnType("float");

                    b.Property<string>("TotalTaxCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TransactionDateConfidence")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("TransactionTime")
                        .HasColumnType("time");

                    b.Property<double?>("TransactionTimeConfidence")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Receipts_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Receipts_UserId_CreatedAt");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptTracker.Core.Entities.Receipt", b =>
                {
                    b.OwnsOne("ReceiptTracker.Core.Models.MerchantAddress", "MerchantAddress", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("CityConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("CountryRegion")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("CountryRegionConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("FullAddress")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<double>("FullAddressConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<double>("HouseNumberConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<double>("PostalCodeConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("Road")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<double>("RoadConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<double>("StateConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("StreetAddress")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<double>("StreetAddressConfidence")
                                .HasColumnType("float");

                            b1.HasKey("ReceiptId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.OwnsMany("ReceiptTracker.Core.Models.ReceiptItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<double>("ContentConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<double>("DescriptionConfidence")
                                .HasColumnType("float");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("PriceConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("PriceCurrency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<double?>("Quantity")
                                .HasColumnType("float");

                            b1.Property<double>("QuantityConfidence")
                                .HasColumnType("float");

                            b1.Property<decimal?>("TotalPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("TotalPriceConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("TotalPriceCurrency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("ReceiptId", "Id");

                            b1.ToTable("ReceiptItem");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.OwnsMany("ReceiptTracker.Core.Models.TaxDetail", "TaxDetails", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal?>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("AmountConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("AmountCurrency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Content")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<double>("ContentConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<double>("DescriptionConfidence")
                                .HasColumnType("float");

                            b1.Property<decimal?>("NetAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("NetAmountConfidence")
                                .HasColumnType("float");

                            b1.Property<string>("NetAmountCurrency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<double?>("Rate")
                                .HasColumnType("float");

                            b1.Property<double>("RateConfidence")
                                .HasColumnType("float");

                            b1.HasKey("ReceiptId", "Id");

                            b1.ToTable("TaxDetail");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.Navigation("Items");

                    b.Navigation("MerchantAddress");

                    b.Navigation("TaxDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
